# -*- coding: utf-8 -*-
"""TASK4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LcpiGN3s26HNFt-pQ5QwVHZr7T9kvSDA
"""

!pip install pandas scikit-learn

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

data = {
    'title': ['Inception', 'The Dark Knight', 'Interstellar', 'The Prestige', 'Memento'],
    'description': [
        'A thief who steals corporate secrets through dream-sharing technology.',
        'Batman faces the Joker, a criminal mastermind causing chaos.',
        'A team of explorers travel through a wormhole in space.',
        'Two magicians engage in a competitive rivalry.',
        'A man with short-term memory loss attempts to track down his wife’s murderer.'
    ]
}

df = pd.DataFrame(data)
df

tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['description'])

cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

indices = pd.Series(df.index, index=df['title']).drop_duplicates()

def recommend(title, cosine_sim=cosine_sim):
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:4]  # Top 3 similar
    movie_indices = [i[0] for i in sim_scores]
    return df['title'].iloc[movie_indices]

print("Recommended for 'Inception':")
print(recommend('Inception'))